[package]
name = "swec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
clap = "4.5.0"
reqwest = "0.11.24"
serde = "1.0.196"
serde_json = "1.0.113"
