[package]
name = "swec"
version = "0.1.0"
edition = "2021"
author = "tarneo"
description = "Simple Web Endpoint Checker"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
reqwest = "0.11.4"
tokio = { version = "1.27.0", features = ["full"] }
