[package]
name = "swec-client-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.35"
reqwest = { version = "0.11.24", features = ["json"] }
syn = "2.0.50"

[lib]
proc-macro = true
